controller_manager:
  ros__parameters:
    update_rate: 30 # integer
    # use_sim_time: True

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_controller:
      type: diff_drive_controller/DiffDriveController

diff_controller:
  ros__parameters:
    publish_rate: 50.0 # double

    odom_frame_id: odom
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.32
    # 0.330

    wheel_radius: 0.0325
    # 0.0335

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    use_stamped_vel: True
    enable_odom_tf: True
