<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
   
   <!-- Dehumidifier -->
   <joint name="dehumidifier_joint" type="fixed">
      <origin xyz="${base_link_xoff} 0 ${(0.170/2) + base_height}" rpy="0 0 0"/>
      <parent link="chassis_link"/>
      <child link="dehumidifier_link"/>
   </joint>

   <link name="dehumidifier_link">
      <visual>
         <geometry>
            <box size="0.048 0.196 0.170"/>
         </geometry>
         <material name="black"/>
      </visual>

      <collision>
         <geometry>
            <box size="0.048 0.196 0.170"/>
         </geometry>
      </collision>
   </link>

   <gazebo reference="dehumidifier_link">
      <material>Gazebo/Black</material>
   </gazebo>

</robot>