<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

   <joint name="lidar_joint" type="fixed">
      <origin xyz="0.0 0.0 ${base_height+0.215}" rpy="0.0 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="lidar_link"/>
   </joint>

   <link name="lidar_link">
      <visual>
         <origin xyz="0.0565 0.031 -0.05" rpy="${pi/2} 0.0 -${pi/2}"/>
         <geometry>
               <mesh filename="package://humibot_description/meshes/ld06.stl" scale="0.001 0.001 0.001"/>
         </geometry>
      </visual>
      
      <visual name="lidar_stand_visual">
         <origin xyz="0.0 0.0 -0.0425" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="0.070 0.066 0.005"/>
         </geometry>
      </visual>
   </link>

   <gazebo reference="lidar_link">
      <material>Gazebo/Red</material>
      <sensor name="lidar" type="ray">
         <always_on>true</always_on>
         <visualize>false</visualize>
         <update_rate>10</update_rate>
         <ray>
            <scan>
               <horizontal>
                  <samples>360</samples>
                  <resolution>1.000000</resolution>
                  <min_angle>0.000000</min_angle>
                  <max_angle>6.280000</max_angle>
               </horizontal>
            </scan>
            <range>
               <min>0.02</min>
               <max>12</max>
               <resolution>0.015000</resolution>
            </range>
            <noise>
               <type>gaussian</type>
               <mean>0.0</mean>
               <stddev>0.01</stddev>
             </noise>
         </ray>
         <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
            <ros>
              <remapping>~/out:=scan</remapping>
            </ros>
            <output_type>sensor_msgs/LaserScan</output_type>
            <frame_name>lidar_link</frame_name>
          </plugin>
      </sensor>
   </gazebo>
</robot>