<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

   <!-- BASE FOOTPRINT -->
   <link name="base_footprint">
   </link>

   <!-- BASE LINK -->
   <joint name="base_joint" type="fixed">
      <!-- -${0.0125 + 0.005} -->
      <origin xyz="0 0 -${wheel_zoff + wheel_radius}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="base_footprint"/>
   </joint>

   <link name="base_link">
   </link>

   <!-- CHASSIS -->
   <joint name="chassis_joint" type="fixed">
      <origin xyz="-${base_link_xoff + 0.0365} 0 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="chassis_link"/>
   </joint>

   <link name="chassis_link">
      <visual>
         <origin xyz="${(base_length/2) + 0.0365} 0.0 ${base_height/2}" rpy="0.0 0.0 ${-(pi/2)}"/>
         <geometry>
            <mesh filename="package://humibot_description/meshes/chassis.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="white"/>
      </visual>
      <collision>
         <origin xyz="${(base_length+0.0365)/2} 0.0 ${(base_height+0.165)/2}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="${base_length + 0.04} ${base_width} ${base_height+0.165}"/>
         </geometry>
      </collision>

      <visual name="left_dc_motor_visual">
         <origin xyz="${base_link_xoff + 0.0365} ${(base_width/2) - (0.063/2)} -${0.0125 + 0.005}" rpy="-${pi/2} 0 0"/>
         <geometry>
            <cylinder radius="0.0125" length="0.063"/>
         </geometry>
         <material name="blue"/>
      </visual>
      <collision name="left_dc_motor_collision">
         <origin xyz="${base_link_xoff + 0.0365} ${(base_width/2) - (0.063/2)} -${0.0125 + 0.005}" rpy="-${pi/2} 0 0"/>
         <geometry>
            <cylinder radius="0.0125" length="0.063"/>
         </geometry>
      </collision>
      
      <visual name="right_dc_motor_visual">
         <origin xyz="${base_link_xoff + 0.0365} -${(base_width/2) - (0.063/2)} -${0.0125 + 0.005}" rpy="-${pi/2} 0 0"/>
         <geometry>
            <cylinder radius="0.0125" length="0.063"/>
         </geometry>
         <material name="blue"/>
      </visual>
      <collision name="right_dc_motor_collision">
         <origin xyz="${base_link_xoff + 0.0365} -${(base_width/2) - (0.063/2)} -${0.0125 + 0.005}" rpy="-${pi/2} 0 0"/>
         <geometry>
            <cylinder radius="0.0125" length="0.063"/>
         </geometry>
      </collision>
      
      <xacro:inertial_box mass="${base_mass}" x="${base_length + 0.04}" y="${base_width}" z="${base_height+0.165}">
         <origin xyz="${base_link_xoff + 0.037} 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>

   <!-- LEFT WHEEL -->
   <joint name="left_wheel_joint" type="continuous">
      <origin xyz="0 ${(base_width/2) + (wheel_width/2) + wheel_ygap} -${0.0125 + 0.005}" rpy="${-(pi/2)} 0 0"/>
      <parent link="base_link"/>
      <child link="left_wheel_link"/>
      <axis xyz="0 0 1"/>
   </joint>

   <link name="left_wheel_link">
      <visual>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
         </geometry>
         <material name="black"/>
      </visual>

      <collision>
         <geometry>
            <sphere radius="${wheel_radius}"/>
         </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
         <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
   </link>

   <!-- RIGHT WHEEL -->
   <joint name="right_wheel_joint" type="continuous">
      <origin xyz="0 -${(base_width/2) + (wheel_width/2) + wheel_ygap} -${0.0125 + 0.005}" rpy="${pi/2} 0 0"/>
      <parent link="base_link"/>
      <child link="right_wheel_link"/>
      <axis xyz="0 0 -1"/>
   </joint>

   <link name="right_wheel_link">
      <visual>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
         </geometry>
         <material name="black"/>
      </visual>

      <collision>
         <geometry>
            <sphere radius="${wheel_radius}"/>
         </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
         <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
   </link>

   <!-- CASTER WHEEL -->
   <joint name="front_caster_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="front_caster"/>
      <origin xyz="${base_length - 0.034} 0 ${-0.0125 - 0.005 + caster_radius - wheel_radius}" rpy="0 0 0"/>
   </joint>

   <link name="front_caster">
      <visual>
         <geometry>
            <sphere radius="${caster_radius}"/>
         </geometry>
         <material name="black"/>
      </visual>

      <collision>
         <geometry>
            <sphere radius="${caster_radius}"/>
         </geometry>
      </collision>

      <visual name="caster_wheel_holder_visual">
         <origin xyz="0.0 0.0 ${0.04/2}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="0.015 0.015 0.04"/>
         </geometry>
      </visual>

      <xacro:inertial_sphere mass="${caster_mass}" radius="${caster_radius}">
         <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_sphere>
   </link>

   <joint name="back_caster_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="back_caster"/>
      <origin xyz="${(0.015/2) + 0.01} 0 ${-0.0125 - 0.005 + caster_radius - wheel_radius}" rpy="0 0 0"/>
   </joint>

   <link name="back_caster">
      <visual>
         <geometry>
            <sphere radius="${caster_radius}"/>
         </geometry>
         <material name="black"/>
      </visual>

      <collision>
         <geometry>
            <sphere radius="${caster_radius}"/>
         </geometry>
      </collision>

      <visual name="caster_wheel_holder_visual">
         <origin xyz="0.0 0.0 ${0.04/2}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="0.015 0.015 0.04"/>
         </geometry>
      </visual>

      <xacro:inertial_sphere mass="${caster_mass}" radius="${caster_radius}">
         <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_sphere>
   </link>

   <!-- GAZEBO -->
   <gazebo reference="chassis_link">
      <material>Gazebo/White</material>
   </gazebo>

   <gazebo reference="left_wheel_link">
      <material>Gazebo/Black</material>
   </gazebo>
   
   <gazebo reference="right_wheel_link">
      <material>Gazebo/Black</material>
   </gazebo>

   <gazebo reference="front_caster">
      <material>Gazebo/Black</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
   </gazebo>

   <gazebo reference="back_caster">
      <material>Gazebo/Black</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
   </gazebo>

</robot>