<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

   <!-- BASE LINK -->
   <link name="base_link">
   </link>

   <!-- CHASSIS -->
   <joint name="chassis_joint" type="fixed">
      <origin xyz="-${base_link_xoff} 0 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="chassis_link"/>
   </joint>

   <link name="chassis_link">
      <visual>
         <origin xyz="${base_length/2} 0.0 ${base_height/2}" rpy="0.0 0.0 ${-(pi/2)}"/>
         <geometry>
            <mesh filename="package://humibot_description/meshes/base.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="white"/>
      </visual>
      <collision>
         <origin xyz="${base_length/2} 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
         </geometry>
      </collision>

      <visual name="base_roof_visual">
         <origin xyz="${base_link_xoff + 0.048} 0 ${base_height+0.02}" rpy="0 0 -${pi/2}"/>
         <geometry>
            <mesh filename="package://humibot_description/meshes/roof.stl" scale="0.001 0.001 0.001"/>
         </geometry>
      </visual>
      <collision name="base_roof_collision">
         <origin xyz="${base_link_xoff + 0.048} 0 ${base_height+0.02}" rpy="0 0 -${pi/2}"/>
         <geometry>
            <mesh filename="package://humibot_description/meshes/roof.stl" scale="0.001 0.001 0.001"/>
         </geometry>
      </collision>

      <!-- <visual name="filter_visual">
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="0.025 0.139 0.150"/>
         </geometry>
      </visual> -->

      <visual name="left_dc_motor_visual">
         <origin xyz="${base_link_xoff} ${(base_width/2) - (0.063/2)} -0.0125" rpy="-${pi/2} 0 0"/>
         <geometry>
            <cylinder radius="0.0125" length="0.063"/>
         </geometry>
         <material name="blue"/>
      </visual>
      <collision name="left_dc_motor_collision">
         <origin xyz="${base_link_xoff} ${(base_width/2) - (0.063/2)} -0.0125" rpy="-${pi/2} 0 0"/>
         <geometry>
            <cylinder radius="0.0125" length="0.063"/>
         </geometry>
      </collision>
      
      <visual name="right_dc_motor_visual">
         <origin xyz="${base_link_xoff} -${(base_width/2) - (0.063/2)} -0.0125" rpy="-${pi/2} 0 0"/>
         <geometry>
            <cylinder radius="0.0125" length="0.063"/>
         </geometry>
         <material name="blue"/>
      </visual>
      <collision name="right_dc_motor_collision">
         <origin xyz="${base_link_xoff} -${(base_width/2) - (0.063/2)} -0.0125" rpy="-${pi/2} 0 0"/>
         <geometry>
            <cylinder radius="0.0125" length="0.063"/>
         </geometry>
      </collision>
      
      <xacro:inertial_box mass="1.012" x="${base_length}" y="${base_width}" z="${base_height}">
         <origin xyz="${base_length/2} 0.0 ${base_height/2}" rpy="0.0 0.0 ${-(pi/2)}"/>
      </xacro:inertial_box>
   </link>

   <!-- Dehumidifier -->
   <xacro:include filename="sensors/dehumidifier.xacro"/>

   <!-- LEFT WHEEL -->
   <joint name="left_wheel_joint" type="continuous">
      <origin xyz="0 ${(base_width/2) + (wheel_width/2) + wheel_ygap} -0.0125" rpy="${-(pi/2)} 0 0"/>
      <parent link="base_link"/>
      <child link="left_wheel_link"/>
      <axis xyz="0 0 1"/>
   </joint>

   <link name="left_wheel_link">
      <visual>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
         </geometry>
         <material name="black"/>
      </visual>

      <collision>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
         </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
         <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
   </link>

   <!-- RIGHT WHEEL -->
   <joint name="right_wheel_joint" type="continuous">
      <origin xyz="0 -${(base_width/2) + (wheel_width/2) + wheel_ygap} -0.0125" rpy="${pi/2} 0 0"/>
      <parent link="base_link"/>
      <child link="right_wheel_link"/>
      <axis xyz="0 0 -1"/>
   </joint>

   <link name="right_wheel_link">
      <visual>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
         </geometry>
         <material name="black"/>
      </visual>

      <collision>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
         </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
         <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
   </link>

   <!-- CASTER WHEEL -->
   <joint name="caster_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="front_caster"/>
      <origin xyz="${base_length - 0.034} 0 ${-0.0125+caster_radius-wheel_radius}" rpy="0 0 0"/>
   </joint>

   <link name="front_caster">
      <visual>
         <geometry>
            <sphere radius="${caster_radius}"/>
         </geometry>
         <material name="black"/>
      </visual>

      <collision>
         <geometry>
            <sphere radius="${caster_radius}"/>
         </geometry>
      </collision>

      <xacro:inertial_sphere mass="${caster_mass}" radius="${caster_radius}">
         <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_sphere>
   </link>

   <!-- GAZEBO -->
   <gazebo reference="chassis_link">
      <material>Gazebo/White</material>
   </gazebo>

   <gazebo reference="left_wheel_link">
      <material>Gazebo/Black</material>
   </gazebo>
   
   <gazebo reference="right_wheel_link">
      <material>Gazebo/Black</material>
   </gazebo>

   <gazebo reference="front_caster">
      <material>Gazebo/Black</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
   </gazebo>

</robot>